export type { IconProps } from './types.js'

export { default as SvgActions } from './SvgActions.js'
export { default as SvgBookOpen } from './SvgBookOpen.js'
export { default as SvgCheckCircle } from './SvgCheckCircle.js'
export { default as SvgCircle } from './SvgCircle.js'
export { default as SvgEditBig } from './SvgEditBig.js'
export { default as SvgFileText } from './SvgFileText.js'
export { default as SvgGlobe } from './SvgGlobe.js'
export { default as SvgImage } from './SvgImage.js'
export { default as SvgMaximize2 } from './SvgMaximize2.js'
export { default as SvgSearch } from './SvgSearch.js'
export { default as SvgSearchMenu } from './SvgSearchMenu.js'
export { default as SvgTerminal } from './SvgTerminal.js'
