export type { IconProps } from './types.js'

export { default as SvgActions } from './SvgActions.js'
export { default as SvgBookOpen } from './SvgBookOpen.js'
export { default as SvgCheckCircle } from './SvgCheckCircle.js'
export { default as SvgCircle } from './SvgCircle.js'
export { default as SvgEditBig } from './SvgEditBig.js'
export { default as SvgFileText } from './SvgFileText.js'
export { default as SvgGlobe } from './SvgGlobe.js'
export { default as SvgImage } from './SvgImage.js'
export { default as SvgMaximize2 } from './SvgMaximize2.js'
export { default as SvgSearch } from './SvgSearch.js'
export { default as SvgSearchMenu } from './SvgSearchMenu.js'
export { default as SvgTerminal } from './SvgTerminal.js'
export { default as SvgCheck } from './SvgCheck.js'
export { default as SvgChevronDown } from './SvgChevronDown.js'
export { default as SvgPaperclip } from './SvgPaperclip.js'
export { default as SvgPlusCircle } from './SvgPlusCircle.js'
export { default as SvgSparkle } from './SvgSparkle.js'
export { default as SvgX } from './SvgX.js'
export { default as SvgThumbsUp } from './SvgThumbsUp.js'
export { default as SvgThumbsDown } from './SvgThumbsDown.js'
export { default as SvgCopy } from './SvgCopy.js'
